import Head from 'next/head';
import {BsFillMoonStarsFill} from "react-icons/bs";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Anisha Hirani</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <main>
        <section className="min-h-screen">
          <nav>
          <h1>developedbyAnisha</h1>
          <ul>
            <li><BsFillMoonStarsFill/></li>
            <lli><a href="#">Resume</a></lli>
          </ul>
          </nav>
        </section>
      </main>
    </div>
  )
}
