import Head from 'next/head';
import Image from "next/image";
import reelplaces from "../public/reelplaces-ss.png";
import acebook from "../public/acebook-new.png";
import bnb from "../public/makersbnb.png";
import chitter from "../public/chitter.png";
import bank from "../public/bank.png";
import {BsFillMoonStarsFill} from "react-icons/bs";
import {AiFillGithub} from "react-icons/ai";
import { HiOutlineLink } from "react-icons/hi";
import { useState } from "react";

export default function Projects() {
  const reelplacesRepo = "https://github.com/anisha-11/ReelPlaces";
  const reelplacesLink = "https://reelplaces.herokuapp.com/"
  const acebookRepo = "https://github.com/anisha-11/acebook";
  const bnbRepo = "https://github.com/anisha-11/MakersBnB";
  const chitterRepo = "https://github.com/anisha-11/chitter-challenge";
  const [darkMode, setDarkMode] = useState(false);
  return (
    <div className={darkMode ? 'dark' : ""}>
      <Head>
        <title>Anisha Hirani</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="bg-orange-100 px-0 md:px-20 lg:px-0 dark:bg-teal-600">
        <navbar className="fixed w-full z-20 top-0 left-0 bottom-50 bg-gray-700 py-10 mb-9 flex justify-between dark:bg-gray-700">
          <h1 className='text-xl text-teal-500 dark:text-orange-200 font-bold font-burtons ml-8 tracking-wider'>Developed by Anisha Hirani</h1>
          <ul className="flex items-center">
            <li>
              <BsFillMoonStarsFill onClick={() => setDarkMode(!darkMode)} className='mr-5 cursor-pointer text-2xl'/>
            </li>
            <li>
              <a className="bg-teal-600 hover:bg-teal-700 text-white dark:bg-orange-200 dark:hover:bg-orange-300 dark:text-black px-4 py-2 rounded-md ml-0 mr-4" href="/" target>Home</a>
            </li>
            <li> 
              <a className="bg-teal-600 hover:bg-teal-700 text-white dark:bg-orange-200 dark:hover:bg-orange-300 dark:text-black px-4 py-2 rounded-md ml-0 mr-4" href="/about" target>About</a>
            </li>
            <li> 
              <a className="bg-teal-600 hover:bg-teal-700 text-white dark:bg-orange-200 dark:hover:bg-orange-300 dark:text-black px-4 py-2 rounded-md ml-0 mr-4" href="/projects" target>Projects</a>
            </li>
            <li> 
              <a className="bg-teal-600 hover:bg-teal-700 text-white dark:bg-orange-200 dark:hover:bg-orange-300 dark:text-black px-4 py-2 rounded-md ml-0 mr-4" href="/Anisha Hirani - CV.pdf" target>CV</a>
            </li>
          </ul>
        </navbar>
        <section className="flex flex-wrap:wrap justify-center align-center text-center flex-wrap:wrap items-stretch">
          <div className="h-20 text-5xl py-20 mt-20 text-teal-600 dark:text-orange-200 font-bold">
            <h1 className='mt-3'>PROJECTS</h1>
          </div>
        </section>
        <section className="flex flex-wrap:wrap justify-center align-center text-center flex-wrap:wrap items-stretch">
          <div className='grid grid-cols-3 justify-center items-center ml-auto mr-auto max-w-l'>
            <div className="text-center shadow-lg dark:bg-gray-700 bg-gray-700 shadow-gray-700 dark:shadow-gray-700 p-1.5 rounded-xl my-8 mr-12 ml-12 mx-auto justify-center">
              <Image className="border-solid border-2 dark:border-black rounded-xl" src={reelplaces} width={650} height={200}/>
              <h3 className="text-3xl text-teal-500 dark:text-orange-200 font-extrabold pt-8 pb-2">REELPLACES</h3>
              <p className="text-md py-5 leading-8 text-white dark:text-white md:text-md max-w-xl mx-auto">
                Web-app that allows users to input current location and find the 
                pin pointed nearby filming location of the top 20 movies.
              </p>
              <div className="text-5xl flex justify-center gap-16 py-3 text-teal-600 dark:text-orange-200 md:text-6xl">
                <a className='hover:text-orange-100' href={reelplacesRepo}><AiFillGithub /></a>
                <a className='hover:text-orange-100' href={reelplacesLink}><HiOutlineLink /></a>
              </div>
            </div>
            <div className="text-center bg-gray-700 dark:dark:bg-gray-700 shadow-lg shadow-gray-700 dark:shadow-gray-700 p-1.5 rounded-xl my-8 mr-12 ml-12 mx-auto justify-center">
              <Image className="border-solid border-2 dark:border-black rounded-xl" src={acebook} width={650} height={200} />
              <h3 className="text-3xl text-teal-500 dark:text-orange-200 font-extrabold pt-8 pb-2">ACEBOOK</h3>
              <p className="text-md py-5 leading-8 text-white dark:text-white md:text-md max-w-xl mx-auto">Similar to Facebook using the MERN Stack and allowing users to comment, upload pictures and have fun on this social media platform.</p>
              <div className="text-5xl flex justify-center gap-16 py-3 text-teal-600 dark:text-orange-200 md:text-6xl">
                <a className='hover:text-orange-100' href={acebookRepo}><AiFillGithub /></a>
              </div>
            </div>
            <div className="text-center display-flex dark:bg-gray-700 shadow-lg bg-gray-700 shadow-gray-700 dark:shadow-gray-700 p-1.5 rounded-xl my-8 mr-12 ml-12 mx-auto justify-center">
              <Image className="border-solid border-2 dark:border-black rounded-xl" src={bnb} width={650} height={200} />
              <h3 className="text-3xl  text-teal-500 dark:text-orange-200 font-extrabold pt-8 pb-2">MAKERS-BNB</h3>
              <p className="text-md py-5 leading-8 text-white dark:text-white md:text-md max-w-md mx-auto">First group 
              project with Makers which was similar to AirBnB using 
              Ruby, Sinatra and databases. Allows you to book spaces and rent 
              out a space.
              </p>
              <div className="text-5xl flex justify-center gap-16 py-3 text-teal-600 dark:text-orange-200 md:text-6xl">
                <a className='hover:text-orange-100' href={bnbRepo}><AiFillGithub /></a>
              </div>
            </div>
            <div className="text-center bg-gray-700 dark:dark:bg-gray-700 shadow-lg shadow-gray-700 dark:shadow-gray-700 p-1.5 rounded-xl my-8 mr-12 ml-12 mt-1 mx-auto justify-center">
              <Image className="border-solid border-2 dark:border-black rounded-xl" src={chitter} width={650} height={200} />
              <h3 className="text-3xl text-teal-500 dark:text-orange-200 font-extrabold pt-8 pb-2">CHITTER</h3>
              <p className="text-md py-5 leading-8 text-white dark:text-white md:text-md max-w-xl mx-auto">Similar to Twitter using Ruby, PostgreSQL databases to login, make and view peeps and also have fun on this social media platform.</p>
              <div className="text-5xl flex justify-center gap-16 py-3 text-teal-600 dark:text-orange-200 md:text-6xl">
                <a className='hover:text-orange-100' href={chitterRepo}><AiFillGithub /></a>
              </div>
            </div>
            <div className="text-center bg-gray-700 dark:dark:bg-gray-700 shadow-lg shadow-gray-700 dark:shadow-gray-700 p-1.5 rounded-xl my-8 mr-12 ml-12 mt-1 mx-auto justify-center">
              <Image className="border-solid border-2 dark:border-black rounded-xl" src={bank} width={650} height={200} />
              <h3 className="text-3xl text-teal-500 dark:text-orange-200 font-extrabold pt-8 pb-2">BANK TECH TEST</h3>
              <p className="text-md py-5 leading-8 text-white dark:text-white md:text-md max-w-xl mx-auto">A TDD app that opens a bank account to allow transactions from deposits and withdrawals to take place.</p>
              <div className="text-5xl flex justify-center gap-16 py-3 text-teal-600 dark:text-orange-200 md:text-6xl">
                <a className='hover:text-orange-100' href={chitterRepo}><AiFillGithub /></a>
              </div>
            </div>
          </div>
        </section>
      </main>
    </div>
  );
};