import Head from 'next/head';
import Image from "next/image";
import reelplaces from "../public/reelplaces-ss.png";
import acebook from "../public/acebook-new.png";
import bnb from "../public/makersbnb.png";
import {BsFillMoonStarsFill} from "react-icons/bs";
import { useState } from "react";

export default function Projects() {
  const [darkMode, setDarkMode] = useState(false);
  return (
    <div className={darkMode ? 'dark' : ""}>
      <Head>
        <title>Anisha Hirani</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <section>
          <navbar>
            <h1>
              <ul>
              <li>
                <BsFillMoonStarsFill onClick={() => setDarkMode(!darkMode)} className='ml-8 cursor-pointer text-2xl'/>
              </li>
              <li>
                <a className="bg-teal-600 text-white dark:bg-orange-200 dark:text-black px-4 py-2 rounded-md ml-8 mr-8" href="/Anisha Hirani - CV.pdf" target="_blank">Resume</a>
              </li>
              <li> 
                <a className="bg-teal-600 text-white dark:bg-orange-200 dark:text-black px-4 py-2 rounded-md ml-0 mr-4" href="/about" target>About Me</a>
              </li>
              <li> 
                <a className="bg-teal-600 text-white dark:bg-orange-200 dark:text-black px-4 py-2 rounded-md ml-0 mr-4" href="/" target>Home</a>
              </li>
              <li> 
                <a className="bg-teal-600 text-white dark:bg-orange-200 dark:text-black px-4 py-2 rounded-md ml-0 mr-4" href="/" target>Projects</a>
              </li>
              </ul>
            </h1>
          </navbar>
        </section>
      </main>
    </div>
  );
};